# default: &default
  # adapter: postgresql
  # encoding: unicode
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['HOST_DATABASE_PASSWORD'] %>
  username: <%= ENV['USERNAME_DATABASE_PASSWORD'] %>
  password: <%= ENV['PASSWORD_DATABASE_PASSWORD'] %>
  pool: 5


development:
  <<: *default
  database: jedis_development

test:
  <<: *default
  database: jedis_test

production:
  <<: *default
  database: jedis_production
  username: jedis
  password: <%= ENV['JEDIS_DATABASE_PASSWORD'] %>
